version: '3.9'

services:
#  POSTGRES
  infinity_net_postgres:
    image: postgres:16
    container_name: infinity_net_postgres
    environment:
      POSTGRES_USER: infinity_net_user
      POSTGRES_PASSWORD: TheInfinityNetP@ssw0rd
      POSTGRES_DB: infinitynet
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - infinity-net-data:/var/lib/postgresql/data
      - postgres-init-db:/docker-entrypoint-initdb.d
    networks:
      - infinity-net
    restart: unless-stopped

#  PGADMIN
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@infinitynet.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - infinity_net_postgres
    networks:
      - infinity-net
    restart: unless-stopped

#  REDIS
  redis:
    image: redis:7
    container_name: infinity_net_redis
    ports:
      - "6379:6379"
    networks:
      - infinity-net
    restart: unless-stopped

#  KAFKA
  infinity_net_kafka:
    image: 'bitnami/kafka:3.7.1-debian-12-r4'
    container_name: infinity_net_kafka
    hostname: kafka
    ports:
      - '9094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

networks:
  infinity-net:
    driver: bridge

volumes:
  infinity-net-data:
  pgadmin:
  postgres-init-db:
