version: '3.9'

services:
#  POSTGRES
  infinity_net_postgres:
    image: postgres:16
    container_name: infinity_net_postgres
    environment:
      POSTGRES_USER: infinity_net_user
      POSTGRES_PASSWORD: TheInfinityNetP@ssw0rd
      POSTGRES_DB: infinitynet
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - infinity-net-data:/var/lib/postgresql/data
      - postgres-init-db:/docker-entrypoint-initdb.d
    networks:
      - infinity-net
    restart: unless-stopped

#  PGADMIN
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@infinitynet.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - infinity_net_postgres
    networks:
      - infinity-net
    restart: unless-stopped

#  REDIS
  infinity_net_redis:
    image: redis:7
    container_name: infinity_net_redis
    ports:
      - "6379:6379"
    volumes:
      - infinity-net-redis-data:/data
    networks:
      - infinity-net
    restart: unless-stopped

#  REDIS INSIGHT
  redis_insight:
    image: redislabs/redisinsight:latest
    container_name: redis_insight
    ports:
      - "5540:5540"
    volumes:
      - redis-insight-data:/db
    depends_on:
      - infinity_net_redis
    networks:
      - infinity-net
    restart: always

#  KAFKA
  infinity_net_kafka:
    image: 'bitnami/kafka:3.7.1-debian-12-r4'
    container_name: infinity_net_kafka
    hostname: kafka
    ports:
      - '9094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

  infinity_net_minio:
    image: minio/minio:RELEASE.2024-08-17T01-24-54Z.fips
    container_name: infinity_net_minio
    ports:
      - "9000:9000"
      - "9001:9001" # Mở port này để truy cập Minio Console
    volumes:
      - infinity-net-minio-data:/data # Tạo volume để lưu trữ dữ liệu
    environment:
      MINIO_ROOT_USER: minioadmin # Thay đổi tên người dùng mặc định
      MINIO_ROOT_PASSWORD: minioadmin # Thay đổi mật khẩu mặc định
    command: server /data --console-address ":9001"

networks:
  infinity-net:
    driver: bridge

volumes:
  infinity-net-data:
  pgadmin:
  postgres-init-db:
  infinity-net-redis-data:
  redis-insight-data:
  infinity-net-minio-data:
